### ISSUE TITLE
Unable to install gopack from KAOS

### ISSUE THREAD

**Issue by gongled** [essentialkaos/gopack#2]
Hi there. Unfortunately, I could not install gopack from KAOS repository.

**Comment by andyone** [comment]
Hi! GoPack currently in heavy development and not available in repo (_even testing_). If you want to try this utility, follow manual installation guide (_or you can just clone repo and simply run this utility like other scripts e.g._ `./gopack ...`)

**Comment by andyone** [comment]
@gongled You can subscribe to pull request #1. When it will be merged, utility will be available in testing and release KAOS repo.

**Comment by andyone** [comment]
@gongled Version 1.0.0 released and can be installed from [EK Public Repo](http://release.yum.kaos.io/x86_64/repoview/gopack.html).
